///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LocationDataModelErrorDetail {
/*
{
  "id": "",
  "message": ""
} 
*/

  String? id;
  String? message;

  LocationDataModelErrorDetail({
    this.id,
    this.message,
  });
  LocationDataModelErrorDetail.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['message'] = message;
    return data;
  }
}

class LocationDataModel {
/*
{
  "status": "200",
  "errorDetail": {
    "id": "",
    "message": ""
  },
  "statusMessage": "",
  "tracktime": "22-04-2020 18:48:09",
  "lat": 12.97796,
  "lon": 77.5318,
  "location": "Sri Ganapathi Tours And Travels,Sri Shylangar,Bangalore,Karnataka",
  "speed": 0,
  "direction": 266,
  "odometer": 585.34
} 
*/

  String? status;
  LocationDataModelErrorDetail? errorDetail;
  String? statusMessage;
  String? tracktime;
  double? lat;
  double? lon;
  String? location;
  int? speed;
  int? direction;
  double? odometer;

  LocationDataModel({
    this.status,
    this.errorDetail,
    this.statusMessage,
    this.tracktime,
    this.lat,
    this.lon,
    this.location,
    this.speed,
    this.direction,
    this.odometer,
  });
  LocationDataModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    errorDetail = (json['errorDetail'] != null)
        ? LocationDataModelErrorDetail.fromJson(json['errorDetail'])
        : null;
    statusMessage = json['statusMessage']?.toString();
    tracktime = json['tracktime']?.toString();
    lat = json['lat']?.toDouble();
    lon = json['lon']?.toDouble();
    location = json['location']?.toString();
    speed = json['speed']?.toInt();
    direction = json['direction']?.toInt();
    odometer = json['odometer']?.toDouble();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (errorDetail != null) {
      data['errorDetail'] = errorDetail!.toJson();
    }
    data['statusMessage'] = statusMessage;
    data['tracktime'] = tracktime;
    data['lat'] = lat;
    data['lon'] = lon;
    data['location'] = location;
    data['speed'] = speed;
    data['direction'] = direction;
    data['odometer'] = odometer;
    return data;
  }
}
